// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

type Player struct {
	ID        string
	Nickname  string
	EloRating int64
	CreatedAt string
	UpdatedAt string
	Active    int64
}
